### ISSUE TITLE
getOperatingSystem null version

### ISSUE THREAD

**Issue by jorgheymans** [dblock/oshi#128]
Hi,

for our servers 
```
new SystemInfo().getOperatingSystem().toString()
```

returns
```
GNU/Linux redhat null (null)
```

if the version info (the second null) is not available from the os , could you not also just put the value of os.version system property ? On that same machine it returns
```
2.6.18-348.1.1.el5
```
which looks like the kernel version.

**Comment by dbwiddis** [comment]
Actually it' s the first null that's the version number.  The parenthetical is the code name.   2.6.18 looks like it's actually a Fedora version with codename Zod.  So the ultimate question is, how would/should/could I know this programmatically?

The lowercase "redhat" indicates that it didn't find the `/etc/os-release` or `/etc/lsb-release` file and fell back to a filename match `/etc/redhat-release`.  At present, we don't parse any of the `/etc/*-release` files, but it may be that we should, if we can rely on a consistent format.   

Does `/etc/redhat-release` give useful information on your system?

**Comment by jorgheymans** [comment]
Hard to say about the /etc/redhat-release because we do not have console
access. I can reasonably try out any snapshots, but it will be slow-going
as the deployment process is tedious.

Jorg

**Comment by dbwiddis** [comment]
I could make a snapshot version which spits it out, but I think there is enough consistency in online docs that I can try to parse it blindly.   

By the way, the 2.6.18 version that os.version spits out is actually the Linux Kernel.   I suspect that the `/etc/redhat-release` file would contain the full version name that we want to output, which would likely be:  `Red Hat Enterprise Linux relaese 5.9 (Tikanga)`.  There is a direct cross-reference between kernel and version (knowing that it's red hat) but I hesitate to get so deep into the weeds.

I found a script on [this page](http://linuxmafia.com/faq/Admin/release-files.html) which seems to indicate consistent parsability of the *-release files for Red Hat, SuSE, Mandrake, and Debian, so I think I'll try to go that route here.

**Comment by dbwiddis** [comment]
I've taken a shot at improving the parsing in #129 .  Check out 2.3-SNAPSHOT and see if it's to your liking.

**Comment by jorgheymans** [comment]
FYI i am testing this today, sorry for the delay.

**Comment by jorgheymans** [comment]
i am getting this stacktrace with the 2.3 snapshot

```
2016-04-12 09:52:58,426 ERROR MachineStatsMonitorAction - Unclosed group near index 1
(
 ^
java.util.regex.PatternSyntaxException: Unclosed group near index 1
(
 ^
	at java.util.regex.Pattern.error(Pattern.java:1924) ~[na:1.7.0_51]
	at java.util.regex.Pattern.accept(Pattern.java:1782) ~[na:1.7.0_51]
	at java.util.regex.Pattern.group0(Pattern.java:2857) ~[na:1.7.0_51]
	at java.util.regex.Pattern.sequence(Pattern.java:2018) ~[na:1.7.0_51]
	at java.util.regex.Pattern.expr(Pattern.java:1964) ~[na:1.7.0_51]
	at java.util.regex.Pattern.compile(Pattern.java:1665) ~[na:1.7.0_51]
	at java.util.regex.Pattern.<init>(Pattern.java:1337) ~[na:1.7.0_51]
	at java.util.regex.Pattern.compile(Pattern.java:1022) ~[na:1.7.0_51]
	at java.lang.String.split(String.java:2313) ~[na:1.7.0_51]
	at java.lang.String.split(String.java:2355) ~[na:1.7.0_51]
	at oshi.software.os.linux.LinuxOSVersionInfoEx.init(LinuxOSVersionInfoEx.java:117) ~[oshi-core-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at oshi.software.os.linux.LinuxOSVersionInfoEx.<init>(LinuxOSVersionInfoEx.java:66) ~[oshi-core-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at oshi.software.os.linux.LinuxOperatingSystem.getVersion(LinuxOperatingSystem.java:189) ~[oshi-core-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at oshi.software.os.linux.LinuxOperatingSystem.toString(LinuxOperatingSystem.java:207) ~[oshi-core-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
```

**Comment by dbwiddis** [comment]
Doh.  Need to escape those pesky parenthesis!

Snapshot should be fixed.

**Comment by jorgheymans** [comment]
ok the output i am getting now for getOperatingSystem().toString() is
```
GNU/Linux Red Hat Enterprise Linux Server Red Hat Enterprise Linux Server (Tikanga)
```
seems a bit weird to have the it twice but at least it is working correctly now ?

**Comment by dbwiddis** [comment]
The second RHEL should be a number. I'll look at it later today.

**Comment by dbwiddis** [comment]
Found the problem. Copy/paste where I forgot to change a 0 to a 1.   I *think* it should be good now.

**Comment by jorgheymans** [comment]
are you sure a new snapshot was published ? still getting the same.

**Comment by dbwiddis** [comment]
Yep, double checked and it was published. Just published another one for other code, so if you still have the problem it's something I can't easily figure out.  If it's still doing that can you cut and paste a copy of getOperatingSystem().toJSON() so I can narrow down which field(s) are the problem?

The code does put the entire string into the "Version" field in the case that it can't parse "RELEASE" or "version" strings, but in that case, the family should just be the file name (so you'd get a duplicated "Red Hat" at worst.)

**Comment by dbwiddis** [comment]
Doh!    I see my error.  I have `if (vers != null)` when it should be `if (vers == null)`.  So I was properly parsing and then completely overwriting!

I blame lack of caffeine.  New snapshot within a few minutes.

**Comment by jorgheymans** [comment]
well i just tested and it returns GNU/Linux Red Hat Enterprise Linux Server 5.9 (Tikanga) which seems to be fine. Must have been nexus intermediate caching or something.

this is the jar i tested with (from the manifest)
Build-Time: 2016-04-14 06:25:53
Git-Revision: bbf8d1e020fc28b3ed84e3a313c77c2796d40e7e

**Comment by dbwiddis** [comment]
Glad you said that because the != null was correct... now I have to undo it again!   But looks like we're all set here.

**Comment by jorgheymans** [comment]
@dbwiddis  looks good indeed, thanks a lot for your help !

**Comment by dbwiddis** [comment]
OK!  New snapshot being published which actually should become 2.3 if no other bugs crop up in the next few days.
